### ISSUE TITLE
Show final bid price of a completed & claimed auction

### ISSUE THREAD

**Issue by jorisbontje** [makerdao/weekly-mkr-auction#61]

**Comment by nanexcool** [comment]
The auctionlet is deleted when tokens are claimed, so the only way (right now) to do this is to go to the events and grab the last bid price. For bid history, we check if we have that info in the local node, otherwise we use the Etherscan API to grab the info.

We can do the same thing here. Otherwise, the other solution would be to not delete the auctionlet and just mark it as claimed in the contract?

@jorisbontje please advice!
